name: 🟢 Keep Services Awake

# Run on a schedule
on:
  schedule:
    # every 5 minutes
    - cron:  '*/5 * * * *'
  # also allow manual trigger
  workflow_dispatch:

jobs:
  ping-services:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Express Backend
        run: |
          curl --fail --silent https://express-backend-u8jr.onrender.com/api/health-check \
            && echo "✅ Express OK" \
            || echo "❌ Express failed"
      - name: Ping Python Microservice
        run: |
          curl --fail --silent https://farmiculture.onrender.com/health-check \
            && echo "✅ Python OK" \
            || echo "❌ Python failed"
